const complaints = [
  {
    id: 1,
    owner: 'Никнейм',
    date: '05.12.2021',
    time: '19:11',
    status: 'Открыто',
    text: 'Amet minim mollit non deserunt ullamc. Amet minim mollit non deserunt ullamc. Amet minim mollit non deserunt ullamc.',
    history: [
      {
        id: 1,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:11',
        status: 'Открыто',
        text: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        viewed: true,
      },
      {
        id: 2,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 3,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 4,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 5,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 6,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 7,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
    ]
  },
  {
    id: 2,
    owner: 'Никнейм',
    date: '05.12.2021',
    time: '19:12',
    status: 'Открыто',
    text: 'Amet minim mollit non deserunt ullamc.',
    history: [
      {
        id: 1,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 2,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 3,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 4,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 5,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 6,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 7,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
    ]
  },
  {
    id: 3,
    owner: 'Никнейм',
    date: '05.12.2021',
    time: '19:12',
    status: 'Закрыто',
    text: 'Amet minim mollit non deserunt ullamc.',
    history: [
      {
        id: 1,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 2,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 3,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 4,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 5,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 6,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 7,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
    ]
  },
  {
    id: 4,
    owner: 'Никнейм',
    date: '05.12.2021',
    time: '19:12',
    status: 'Открыто',
    text: 'Amet minim mollit non deserunt ullamc.',
    history: [
      {
        id: 1,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 2,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 3,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 4,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 5,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 6,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 7,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
    ]
  },
  {
    id: 5,
    owner: 'Никнейм',
    date: '05.12.2021',
    time: '19:12',
    status: 'Открыто',
    text: 'Amet minim mollit non deserunt ullamc.',
    history: [
      {
        id: 1,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 2,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 3,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 4,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 5,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 6,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 7,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
    ]
  },
  {
    id: 6,
    owner: 'Никнейм',
    date: '05.12.2021',
    time: '19:12',
    status: 'Открыто',
    text: 'Amet minim mollit non deserunt ullamc.',
    history: [
      {
        id: 1,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 2,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 3,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
      {
        id: 4,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 5,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 6,
        owner: 'Поддержка Infinity',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: false,
      },
      {
        id: 7,
        owner: 'Никнейм',
        date: '05.12.2021',
        time: '19:12',
        status: 'Открыто',
        text: 'Amet minim mollit non deserunt ullamc.',
        viewed: true,
      },
    ]
  }
]
export default complaints